apiVersion: v1
kind: Service
metadata:
  name: book-api-service
spec:
  type: NodePort
  selector:
    app: book-api
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30007
