apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-httpd-frontend
spec:
  selector:
    matchLabels:
      name: httpd-frontend
  template:
    metadata:
      labels: 
        name: httpd-frontend
    spec:
      containers:
        - name: http-alpine
          image: httpd:2.4-alpine
          command:
            - sh
            - "-c"
            - echo Hello Kubernetes! && sleep 3600
  replicas: 3
