apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-api
  template:
    metadata:
      labels:
        app: book-api
    spec:
      containers:
        - name: book-app-api
          image: book-app-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/book?useSSL=false&allowPublicKeyRetrieval=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "bookAdmin"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "Salesforce@1"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_DATABASE-PLATFORM
              value: "org.hibernate.dialect.MySQL8Dialect"
